version: 2.1

orbs:
  sam: circleci/aws-sam-serverless@3.1.0
  

commands:
  destroy-cluster:
    description: Destroy EKS Cluster.
    steps:
      - run:
          name: Destroy environments
          when: on_fail
          command: |
            eksctl delete cluster --name node-app

  install-kubectl-and-eksctl:
    description: install kubectl and eksctl
    steps:
      - run:
          name: Installing kubectl and eksctl
          command: |
                  yum install tar gzip -y
                  curl --silent --location -o /usr/local/bin/kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/kubectl
                  chmod +x /usr/local/bin/kubectl
                  mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
                  kubectl version --client
          
                  curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
                  mv /tmp/eksctl /usr/local/bin
                  eksctl version


jobs:
  lint-app:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Dockerfiles lint
          command: |
            npm install
            npm run lint
  
  build-and-push-node1:
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker container for V1
          command: |
            curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
            sudo apt install nodejs
            node -v
            npm -v
            npm i
            docker build -t  eebru/capstone:v1 .
            docker login -u eebru -p $DOCKERPASS
            docker push eebru/capstone:v1
  
  build-and-push-node2:
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker container for V1
          command: |
            curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
            sudo apt install nodejs
            node -v
            npm -v
            npm i
            docker build -t eebru/capstone:v2 .
            docker login -u eebru -p $DOCKERPASS
            docker push eebru/capstone:v2

  create-eks-cluster-app:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - install-kubectl-and-eksctl
      - run:
          name: Creating K8S cluster
          command: |
                  eksctl create cluster \
                  --name node-app \
                  --region us-west-2 \
                  --with-oidc \
                  --ssh-access \
                  --ssh-public-key udacity
                  kubectl get nodes -o wide
                  kubectl create namespace node-namespace
                  aws eks update-kubeconfig --name node-app --region us-west-2
      - run:
          name: Deploying node-appv1
          command: |
              kubectl apply -f node-appv1.yml
      # - destroy-cluster

  smoke-test-v1:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: |
            yum install jq -y
      - install-kubectl-and-eksctl
      - run:
          name: Get Service URL and curl
          command: |
            kubectl get svc node-service -n node-namespace -o wide
            
      # - destroy-cluster

workflows:
  the_jobs:
    jobs:
      - lint-app
      # - build-and-push-node1:
      #     requires: [lint-app]
      # - build-and-push-node2:
      #     requires: [build-and-push-node1]
      - create-eks-cluster-app
         # # requires: [build-and-push-node1]
      - smoke-test-v1:
          requires: [create-eks-cluster-app]